#!/bin/sh

sudo cp /home/pollution/airquality/serverbuild/disable-transparent-hugepages /etc/init.d/disable-transparent-hugepages

sudo chmod 755 /etc/init.d/disable-transparent-hugepages

sudo update-rc.d disable-transparent-hugepages defaults

echo 'Transparent Huge Pages Disabled.'
