#!/bin/bash

#This script builds the initial environment to host the pollution tracking web app

#Certain commands require sudo so this cannot be automated (must type password when prompted

if [[ $# -ne 2 ]] ; then
    echo 'Usage: install_script "First Last" "email@address.com"'
    echo 'input strings will be used to setup git'
    exit 0
fi

if [[ -d "/home/$(whoami)/airquality" ]] ; then
  echo "/home/$(whoami)/airquality already exists"
  exit 0
fi

#to fix AWS error with sudo "unable to resolve host"
echo "127.0.0.1 $(hostname)" >> /etc/hosts

mkdir /home/$(whoami)/airquality
cd  /home/$(whoami)/airquality

sudo apt-get update
sudo apt-get -y install git
git config --global user.name "$1"
git config --global user.email "$2"
git init

git remote add origin https://github.com/kalomj/Pollution
git pull origin master

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

sudo apt-get update

sudo apt-get install -y mongodb-org=3.0.0 mongodb-org-server=3.0.0 mongodb-org-shell=3.0.0 mongodb-org-mongos=3.0.0 mongodb-org-tools=3.0.0

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
. ~/.nvm/nvm.sh 
. ~/.profile 
. ~/.bashrc
source ~/.profile

nvm install v0.10.25
nvm alias default 0.10.25
(cd node_modules/meanio && npm install request)
(cd node_modules/meanio && npm install uglify-js)
(cd node_modules/meanio && npm install)

npm install -g bower
bower install
npm install -g grunt-cli
npm install -g grunt

npm install

echo 'Install Complete.'
