#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo 'Usage: move_mongo_script src dst'
    echo 'this script assumes mongo_setup_script was used to initially setup mongo, mongo/data and mongo/log folders, with mongo folder under the current user's ownership'
    exit 0
fi

echo 'stop the web server'
grunt --gruntfile /home/pollution/airquality/Gruntfile.js forever:server:stop

echo 'stop the mongo service'
sudo service mongod stop

echo 'copy the mongo directory to a new location'
mv src dst

echo 'update the default path in mongo config'
sudo sed -i -e 's|dbpath=.*$|dbpath='$2'/data|' /etc/mongod.conf
sudo sed -i -e 's|logpath=.*$|logpath='$2'/log/mongod.log|' /etc/mongod.conf

echo 'restart the mongo service'
sudo service mongod start

echo 'restart the web server'
grunt --gruntfile /home/pollution/airquality/Gruntfile.js forever:server:start

echo 'migration complete'
