#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo 'Usage: move_mongo_script src dst'
    echo 'this script assumes mongo_setup_script was used to initially setup mongo, mongo/data and mongo/log folders, with mongo folder under the current user's ownership'
    exit 0
fi

#stop the mongo service
sudo service mongod stop

#copy the mongo directory to a new location
mv src dst

#update the default path in mongo config
sudo sed -i -e 's|dbpath=.*$|dbpath='$2'/data|' /etc/mongod.conf
sudo sed -i -e 's|logpath=.*$|logpath='$2'/log/mongod.log|' /etc/mongod.conf

#restart the mongo service
sudo service mongod start
